// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjA2ooIW5I35OCF5opalIS88SR9y3G_dA',
    appId: '1:855087722830:web:2291ce30e6ecb1413b6e1f',
    messagingSenderId: '855087722830',
    projectId: 'trafficpay-lk',
    authDomain: 'trafficpay-lk.firebaseapp.com',
    storageBucket: 'trafficpay-lk.firebasestorage.app',
    measurementId: 'G-GE4PG3G8SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB71UVlwI9qeFa_w0W2dG9McUfe_XUCVqU',
    appId: '1:855087722830:android:a05367dde99f570b3b6e1f',
    messagingSenderId: '855087722830',
    projectId: 'trafficpay-lk',
    storageBucket: 'trafficpay-lk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGnoh2NNOONKsVYCa37XiBDTgiRCTLDWQ',
    appId: '1:855087722830:ios:0d07e21f159e7c493b6e1f',
    messagingSenderId: '855087722830',
    projectId: 'trafficpay-lk',
    storageBucket: 'trafficpay-lk.firebasestorage.app',
    iosBundleId: 'com.slpolice.trafficpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGnoh2NNOONKsVYCa37XiBDTgiRCTLDWQ',
    appId: '1:855087722830:ios:0d07e21f159e7c493b6e1f',
    messagingSenderId: '855087722830',
    projectId: 'trafficpay-lk',
    storageBucket: 'trafficpay-lk.firebasestorage.app',
    iosBundleId: 'com.slpolice.trafficpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjA2ooIW5I35OCF5opalIS88SR9y3G_dA',
    appId: '1:855087722830:web:d95e3c1313cec3b23b6e1f',
    messagingSenderId: '855087722830',
    projectId: 'trafficpay-lk',
    authDomain: 'trafficpay-lk.firebaseapp.com',
    storageBucket: 'trafficpay-lk.firebasestorage.app',
    measurementId: 'G-6TWCS4SWKE',
  );
}
